TRUNCATE TABLE concert;
TRUNCATE TABLE seat;
TRUNCATE TABLE waiting_queue;
TRUNCATE TABLE reservation;
TRUNCATE TABLE payment;
TRUNCATE TABLE user;
TRUNCATE TABLE outbox;

INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);
INSERT INTO user(balance) VALUES(0);

INSERT INTO concert(name, date) VALUES("The Final Curtain", "2025-07-01");
INSERT INTO concert(name, date) VALUES("The Final Curtain", "2025-07-15");
INSERT INTO concert(name, date) VALUES("The Final Curtain", "2025-08-01");
INSERT INTO concert(name, date) VALUES("The Final Curtain", "2025-10-02");

INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 1, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 2, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 3, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 4, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 5, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 6, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 7, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 8, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 9, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 10, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 11, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 12, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 13, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 14, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 15, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 16, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 17, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 18, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 19, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 20, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 21, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 22, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 23, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 24, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 25, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 26, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 27, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 28, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 29, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 30, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 31, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 32, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 33, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 34, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 35, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 36, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 37, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 38, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 39, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 40, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 41, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 42, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 43, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 44, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 45, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 46, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 47, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 48, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 49, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(1, 50, 10000, "AVAILABLE");

INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 1, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 2, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 3, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 4, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 5, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 6, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 7, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 8, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 9, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 10, 50000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 11, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 12, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 13, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 14, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 15, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 16, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 17, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 18, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 19, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 20, 40000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 21, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 22, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 23, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 24, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 25, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 26, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 27, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 28, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 29, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 30, 30000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 31, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 32, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 33, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 34, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 35, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 36, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 37, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 38, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 39, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 40, 20000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 41, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 42, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 43, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 44, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 45, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 46, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 47, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 48, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 49, 10000, "AVAILABLE");
INSERT INTO seat(concert_id, number, cost, status) VALUES(2, 50, 10000, "AVAILABLE");

--INSERT INTO user(uuid) VALUES("abcd");
--
--INSERT INTO waiting_queue(uuid) VALUES("abcd");
--INSERT INTO waiting_queue(uuid) VALUES("abcd");
--INSERT INTO waiting_queue(uuid) VALUES("abcd");
